### ISSUE TITLE
Add v2ray with ssrpanel installation docs

### ISSUE THREAD

**Issue by ColetteContreras** [ssrpanel/SSRPanel#1222]
Hi,

Recently, I wrote [a V2ray builtin plugin for SSRPanel](https://github.com/ColetteContreras/v2ray-ssrpanel-plugin) which is easy to install and config. It just takes about 5MB to 10MB memories more than v2ray core.

I'll be pleased if you could try it : )

# V2ray with ssrpanel

## Instal

```
curl -L -s https://raw.githubusercontent.com/ColetteContreras/v2ray-ssrpanel-plugin/master/install-release.sh | sudo bash
```

## Demo config

```json
{
  "log": {
    "loglevel": "debug"
  },
  "api": {
    "tag": "api",
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ]
  },
  "stats": {},
  "inbounds": [{
    "port": 10086,
    "protocol": "vmess",
    "tag": "proxy"
  },{
    "listen": "127.0.0.1",
    "port": 10085,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "127.0.0.1"
    },
    "tag": "api"
  }],
  "outbounds": [{
    "protocol": "freedom"
  }],
  "routing": {
    "rules": [{
      "type": "field",
      "inboundTag": [ "api" ],
      "outboundTag": "api"
    }],
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true
    }
  },

  "ssrpanel": {
    // Node id on your SSR Panel
    "nodeId": 1,
    // every N seconds
    "checkRate": 60,
    // user config
    "user": {
      // inbound tag, which inbound you would like add user to
      "inboundTag": "proxy",
      "level": 0,
      "alterId": 16,
      "security": "none"
    },
    // db connection
    "mysql": {
      "host": "127.0.0.1",
      "port": 3306,
      "user": "root",
      "password": "ssrpanel",
      "dbname": "ssrpanel"
    }
  }
}
```

**Comment by ssrpanel** [comment]
能否留下你的telegram 号，我邀请你进群交流

**Comment by ssrpanel** [comment]
谢谢大佬

**Comment by ColetteContreras** [comment]
@ssrpanel Thanks of all, sorry about that i couldn't join the telegram. we could communicate with each other by sending emails.

Waiting for your trial experience with [my SSRPanel plugin](https://github.com/ColetteContreras/v2ray-ssrpanel-plugin)!

**Comment by samac08** [comment]
> 谢谢大佬
@ssrpanel @ColetteContreras    v2 ratio calculation problem
The flow ratio calculation is invalid..
Not calculated according to the node setting ratio eg: 5
eg: node setting 5, actually calculated according to 1:1

<a href="https://imgchr.com/i/FWnhuj"><img src="https://s1.ax1x.com/2018/12/28/FWnhuj.md.png" alt="FWnhuj.png" border="0" /></a>
<a href="https://imgchr.com/i/FWui8O"><img src="https://s1.ax1x.com/2018/12/28/FWui8O.md.png" alt="FWui8O.png" border="0" /></a>

**Comment by ssrpanel** [comment]
@samac08 it could be is bug or the author @ColetteContreras did not add the function

**Comment by samac08** [comment]
> @samac08 it could be is bug or the author @ColetteContreras did not add the function
I also tested the java backend. The same problem 1:1 ; ratio calculation is invalid...

**Comment by ColetteContreras** [comment]
@samac08 It seems that i forgot to do a multiplication.
@ssrpanel Should i do the multiplication before saving upload/download traffic to database?

**Comment by ColetteContreras** [comment]
@Hamishcn I released a new version which will fix this problem. you could try it. i appreciate your response.

**Comment by samac08** [comment]
> @Hamishcn I released a new version, [v0.2.2](https://github.com/ColetteContreras/v2ray-ssrpanel-plugin/releases/tag/v0.2.2), which fixed this problem. You could try it, let me know if it's still have this problem! @ColetteContreras  @ssrpanel 
1. The flow ratio calculation is invalid.. ----new v0.2.2 
2. Since the default administrator admin is not the full emil format.The same configuration now tip "invalid user" .
3. actually calculated according to 1:1 ,not do arithmetic.
4. same configurationseting  nothing do changes.
<a href="https://imgchr.com/i/F7KlXq"><img src="https://s2.ax1x.com/2019/01/05/F7KlXq.md.png" alt="F7KlXq.png" border="0" /></a>

**Comment by ssrpanel** [comment]
@Hamishcn 
1.node server's timezone must set to CST 
2.install ntpdate and sync your node server's system time
3.confirm your node server's time same as your local clients's system time

**Comment by ssrpanel** [comment]
@ColetteContreras It seems not work!
I run uninstall script and the run install script for update to the latest version.
But the problem still exists.
The node's traffic ratio has been set to 5

CentOS 7 64 bit
```
^C[root@node2 etc]# /usr/bin/v2ray/v2ray -config /etc/v2ray/config.json 
V2Ray 4.9 (Po) Custom
A unified platform for anti-censorship.
2019/01/07 16:11:10 [Debug] v2ray.com/core/app/log: Logger started
2019/01/07 16:11:10 [Warning] v2ray.com/core: V2Ray 4.9 started
2019/01/07 16:11:11 [Info] SSRPanelPlugin: Connecting database...
2019/01/07 16:11:11 [Info] SSRPanelPlugin: Connected
2019/01/07 16:11:12 [Warning] SSRPanelPlugin: Connected gRPC server "127.0.0.1:10085" 
2019/01/07 16:11:12 [Debug] [2751985067] v2ray.com/core/proxy/dokodemo: processing connection from: 127.0.0.1:47698
2019/01/07 16:11:12 [Info] [2751985067] v2ray.com/core/app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2019/01/07 16:11:12 [Debug] SSRPanelPlugin: node[13] traffic rate 5.00
2019/01/07 16:11:12 [Debug] SSRPanelPlugin: Added user: id=1, VmessID=aada1ddb-c7b2-0b42-716e-78917de75f8d, Email=admin

2019/01/07 16:11:38 [Info] [3192668119] v2ray.com/core/proxy/vmess/inbound: received request for tcp:v1.mux.cool:0
2019/01/07 16:11:38 [Info] [3192668119] v2ray.com/core/common/mux: received request for tcp:speedtest.dallas.linode.com:80
2019/01/07 16:11:38 [Debug] v2ray.com/core/app/stats: create new counter user>>>admin>>>traffic>>>uplink
2019/01/07 16:11:38 [Debug] v2ray.com/core/app/stats: create new counter user>>>admin>>>traffic>>>downlink
2019/01/07 16:11:38 tcp:222.22.68.156:50548 accepted tcp:speedtest.dallas.linode.com:80 
2019/01/07 16:11:38 [Info] [3192668119] v2ray.com/core/app/dispatcher: default route for tcp:speedtest.dallas.linode.com:80
2019/01/07 16:11:38 [Info] [3192668119] v2ray.com/core/proxy/freedom: opening connection to tcp:speedtest.dallas.linode.com:80
2019/01/07 16:11:38 [Info] [3192668119] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:speedtest.dallas.linode.com:80
2019/01/07 16:12:15 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 49.5M, ↑ 827B, online 1
2019/01/07 16:12:31 [Info] [3192668119] v2ray.com/core/common/mux: received request for tcp:myssl.com:443
2019/01/07 16:12:31 tcp:222.22.68.156:50548 accepted tcp:myssl.com:443 
2019/01/07 16:12:31 [Info] [3192668119] v2ray.com/core/app/dispatcher: default route for tcp:myssl.com:443
2019/01/07 16:12:31 [Info] [3192668119] v2ray.com/core/proxy/freedom: opening connection to tcp:myssl.com:443
2019/01/07 16:12:31 [Info] [3192668119] v2ray.com/core/transport/internet/tcp: dialing TCP to tcp:myssl.com:443
2019/01/07 16:13:15 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 50.5M, ↑ 1.1K, online 1
2019/01/07 16:13:47 [Info] [3192668119] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/vmess/inbound: connection ends > context canceled
2019/01/07 16:14:15 [Debug] SSRPanelPlugin: + 0 users, - 0 users, ↓ 77B, ↑ 0, online 1
```
